twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locales: '%app.locales%'
    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
