vich_uploader:
    db_driver: orm

    mappings:
        manual:
            uri_prefix: '%env(resolve:APP_PATH)%/public/motherboard/manual'
            upload_destination: '%kernel.project_dir%/public/motherboard/manual'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        bios:
            uri_prefix: '%env(resolve:APP_PATH)%/public/motherboard/bios'
            upload_destination: '%kernel.project_dir%/public/motherboard/bios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image:
            uri_prefix: '%env(resolve:APP_PATH)%/public/motherboard/image'
            upload_destination: '%kernel.project_dir%/public/motherboard/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
