vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        manual:
            uri_prefix: /motherboard/manual
            upload_destination: '%kernel.project_dir%/public/motherboard/manual'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        miscfile:
            uri_prefix: /motherboard/miscfile
            upload_destination: '%kernel.project_dir%/public/motherboard/miscfile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        chipsetDoc:
            uri_prefix: /chipset/documentation
            upload_destination: '%kernel.project_dir%/public/chipset/documentation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        chipDoc:
            uri_prefix: /chip/documentation
            upload_destination: '%kernel.project_dir%/public/chip/documentation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        bios:
            uri_prefix: /motherboard/bios
            upload_destination: '%kernel.project_dir%/public/motherboard/bios'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image:
            uri_prefix: /motherboard/image
            upload_destination: '%kernel.project_dir%/public/motherboard/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        chipimage:
            uri_prefix: '/chip/image'
            upload_destination: '%kernel.project_dir%/public/chip/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        largefile:
            uri_prefix: '/uploads'
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'subdirectory', transliterate: true }
        osicon:
            uri_prefix: '/icons/os'
            upload_destination: '%kernel.project_dir%/public/icons/os'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        mediatypeicon:
            uri_prefix: '/icons/mediatype'
            upload_destination: '%kernel.project_dir%/public/icons/mediatype'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
