-- Doctrine Migration File Generated on 2021-07-23 21:33:03

-- Version DoctrineMigrations\Version20210723191649
DROP SEQUENCE chipset_part_id_seq CASCADE;
DROP SEQUENCE coprocessor_id_seq CASCADE;
DROP SEQUENCE processor_id_seq CASCADE;
CREATE SEQUENCE cache_method_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE cache_ratio_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE chip_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE chip_alias_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE chip_image_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE chipset_bios_code_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE cpu_socket_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE dump_quality_flag_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE id_redirection_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE instruction_set_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE large_file_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE large_file_chipset_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE large_file_media_type_flag_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE large_file_motherboard_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE large_file_os_flag_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE manufacturer_bios_manufacturer_code_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE media_type_flag_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE os_family_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE os_flag_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE processor_voltage_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE chip_alias (id INT NOT NULL, chip_id INT NOT NULL, manufacturer_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, part_number VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_C7BBB9A9A588ADB3 ON chip_alias (chip_id);
CREATE INDEX IDX_C7BBB9A9A23B42D ON chip_alias (manufacturer_id);
CREATE TABLE chip_image (id INT NOT NULL, chip_id INT NOT NULL, creditor_id INT DEFAULT NULL, license_id INT NOT NULL, file_name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_E3EAD662A588ADB3 ON chip_image (chip_id);
CREATE INDEX IDX_E3EAD662DF91AC92 ON chip_image (creditor_id);
CREATE INDEX IDX_E3EAD662460F904B ON chip_image (license_id);
CREATE TABLE chipset_bios_code (id INT NOT NULL, chipset_id INT NOT NULL, bios_manufacturer_id INT NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_6DA11F9FBC1433B9 ON chipset_bios_code (chipset_id);
CREATE INDEX IDX_6DA11F9FE209FBA6 ON chipset_bios_code (bios_manufacturer_id);
CREATE TABLE cpu_socket_processor_platform_type (cpu_socket_id INT NOT NULL, processor_platform_type_id INT NOT NULL, PRIMARY KEY(cpu_socket_id, processor_platform_type_id));
CREATE INDEX IDX_2CD1411C6B6A65A0 ON cpu_socket_processor_platform_type (cpu_socket_id);
CREATE INDEX IDX_2CD1411CA90B5CBC ON cpu_socket_processor_platform_type (processor_platform_type_id);
CREATE TABLE dump_quality_flag (id INT NOT NULL, name VARCHAR(255) NOT NULL, tag_name VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE TABLE id_redirection (id INT NOT NULL, source INT NOT NULL, source_type VARCHAR(255) NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE TABLE instruction_set_instruction_set (instruction_set_source INT NOT NULL, instruction_set_target INT NOT NULL, PRIMARY KEY(instruction_set_source, instruction_set_target));
CREATE INDEX IDX_A5925A66FCDF0C77 ON instruction_set_instruction_set (instruction_set_source);
CREATE INDEX IDX_A5925A66E53A5CF8 ON instruction_set_instruction_set (instruction_set_target);
CREATE TABLE large_file (id INT NOT NULL, dump_quality_flag_id INT NOT NULL, name VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, subdirectory VARCHAR(255) NOT NULL, file_version VARCHAR(255) DEFAULT NULL, has_activation_key BOOLEAN NOT NULL, has_copy_protection BOOLEAN NOT NULL, note VARCHAR(2048) DEFAULT NULL, release_date DATE DEFAULT NULL, date_precision VARCHAR(1) DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_8C8CD216398716CD ON large_file (dump_quality_flag_id);
CREATE TABLE large_file_language (large_file_id INT NOT NULL, language_id INT NOT NULL, PRIMARY KEY(large_file_id, language_id));
CREATE INDEX IDX_473D2A6A29EA72E8 ON large_file_language (large_file_id);
CREATE INDEX IDX_473D2A6A82F1BAF4 ON large_file_language (language_id);
CREATE TABLE large_file_chipset (id INT NOT NULL, large_file_id INT NOT NULL, chipset_id INT NOT NULL, is_recommended BOOLEAN NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_CA790FD229EA72E8 ON large_file_chipset (large_file_id);
CREATE INDEX IDX_CA790FD2BC1433B9 ON large_file_chipset (chipset_id);
CREATE TABLE large_file_media_type_flag (id INT NOT NULL, large_file_id INT NOT NULL, media_type_flag_id INT NOT NULL, count INT NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_10386AB129EA72E8 ON large_file_media_type_flag (large_file_id);
CREATE INDEX IDX_10386AB1D04F219C ON large_file_media_type_flag (media_type_flag_id);
CREATE TABLE large_file_motherboard (id INT NOT NULL, large_file_id INT NOT NULL, motherboard_id INT NOT NULL, is_recommended BOOLEAN NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_E989BE6729EA72E8 ON large_file_motherboard (large_file_id);
CREATE INDEX IDX_E989BE676511E8A3 ON large_file_motherboard (motherboard_id);
CREATE TABLE large_file_os_flag (id INT NOT NULL, large_file_id INT NOT NULL, os_flag_id INT NOT NULL, unsure BOOLEAN NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_C873B20C29EA72E8 ON large_file_os_flag (large_file_id);
CREATE INDEX IDX_C873B20C8ABD126A ON large_file_os_flag (os_flag_id);
CREATE TABLE manufacturer_bios_manufacturer_code (id INT NOT NULL, manufacturer_id INT NOT NULL, bios_manufacturer_id INT NOT NULL, code VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_992235C6A23B42D ON manufacturer_bios_manufacturer_code (manufacturer_id);
CREATE INDEX IDX_992235C6E209FBA6 ON manufacturer_bios_manufacturer_code (bios_manufacturer_id);
CREATE TABLE media_type_flag (id INT NOT NULL, name VARCHAR(255) NOT NULL, tag_name VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id));
CREATE TABLE motherboard_id_redirection (id INT NOT NULL, destination_id INT NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_30FFE83E816C6140 ON motherboard_id_redirection (destination_id);
CREATE TABLE os_family (id INT NOT NULL, name VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id));
CREATE TABLE os_flag (id INT NOT NULL, manufacturer_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, major_version VARCHAR(255) NOT NULL, minor_version VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_27D7F081A23B42D ON os_flag (manufacturer_id);
CREATE TABLE os_flag_os_family (os_flag_id INT NOT NULL, os_family_id INT NOT NULL, PRIMARY KEY(os_flag_id, os_family_id));
CREATE INDEX IDX_52DAADA18ABD126A ON os_flag_os_family (os_flag_id);
CREATE INDEX IDX_52DAADA12B9B9EE5 ON os_flag_os_family (os_family_id);
CREATE TABLE processing_unit_cpu_socket (processing_unit_id INT NOT NULL, cpu_socket_id INT NOT NULL, PRIMARY KEY(processing_unit_id, cpu_socket_id));
CREATE INDEX IDX_DB937A2B93E55C96 ON processing_unit_cpu_socket (processing_unit_id);
CREATE INDEX IDX_DB937A2B6B6A65A0 ON processing_unit_cpu_socket (cpu_socket_id);
CREATE TABLE processor_platform_type_motherboard (processor_platform_type_id INT NOT NULL, motherboard_id INT NOT NULL, PRIMARY KEY(processor_platform_type_id, motherboard_id));
CREATE INDEX IDX_91AC6702A90B5CBC ON processor_platform_type_motherboard (processor_platform_type_id);
CREATE INDEX IDX_91AC67026511E8A3 ON processor_platform_type_motherboard (motherboard_id);
CREATE TABLE processor_platform_type_processor_platform_type (processor_platform_type_source INT NOT NULL, processor_platform_type_target INT NOT NULL, PRIMARY KEY(processor_platform_type_source, processor_platform_type_target));
CREATE INDEX IDX_FFE4AFE1F2B96AA2 ON processor_platform_type_processor_platform_type (processor_platform_type_source);
CREATE INDEX IDX_FFE4AFE1EB5C3A2D ON processor_platform_type_processor_platform_type (processor_platform_type_target);
CREATE TABLE processor_voltage (id INT NOT NULL, processor_id INT NOT NULL, value DOUBLE PRECISION NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_D614E2FE37BAC19A ON processor_voltage (processor_id);
DROP TABLE migration_versions;
DROP INDEX idx_aab5aea3a23b42d;
ALTER TABLE chipset_part DROP manufacturer_id;
ALTER TABLE chipset_part DROP name;
ALTER TABLE chipset_part DROP chip_no;
ALTER TABLE chipset_part ADD CONSTRAINT FK_AAB5AEA3BF396750 FOREIGN KEY (id) REFERENCES chip (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE chipset_part ADD PRIMARY KEY (id);
ALTER TABLE cpu_speed ADD PRIMARY KEY (id);
ALTER TABLE creditor ADD PRIMARY KEY (id);
ALTER TABLE dram_type ADD PRIMARY KEY (id);
ALTER TABLE expansion_slot ADD hidden_search BOOLEAN;
ALTER TABLE expansion_slot ADD PRIMARY KEY (id);
ALTER TABLE form_factor ADD PRIMARY KEY (id);
ALTER TABLE io_port ADD PRIMARY KEY (id);
ALTER TABLE known_issue ADD PRIMARY KEY (id);
ALTER TABLE license ADD PRIMARY KEY (id);
ALTER TABLE manual ADD PRIMARY KEY (id);
ALTER TABLE manufacturer ADD PRIMARY KEY (id);
ALTER TABLE max_ram ADD PRIMARY KEY (id);
DROP INDEX idx_7f7a0f2ba90b5cbc;
ALTER TABLE motherboard DROP processor_platform_type_id;
ALTER TABLE motherboard ADD PRIMARY KEY (id);
ALTER TABLE motherboard_processor_platform_type ALTER motherboard_id SET NOT NULL;
ALTER TABLE motherboard_processor_platform_type ALTER processor_platform_type_id SET NOT NULL;
CREATE INDEX IDX_417BADED6511E8A3 ON motherboard_processor_platform_type (motherboard_id);
CREATE INDEX IDX_417BADEDA90B5CBC ON motherboard_processor_platform_type (processor_platform_type_id);
ALTER TABLE motherboard_processor_platform_type ADD PRIMARY KEY (motherboard_id, processor_platform_type_id);
ALTER TABLE motherboard_processor ALTER motherboard_id SET NOT NULL;
ALTER TABLE motherboard_processor ALTER processor_id SET NOT NULL;
CREATE INDEX IDX_2BE8FD216511E8A3 ON motherboard_processor (motherboard_id);
CREATE INDEX IDX_2BE8FD2137BAC19A ON motherboard_processor (processor_id);
ALTER TABLE motherboard_processor ADD PRIMARY KEY (motherboard_id, processor_id);
ALTER TABLE motherboard_cpu_speed ADD PRIMARY KEY (motherboard_id, cpu_speed_id);
ALTER TABLE motherboard_cache_size ADD PRIMARY KEY (motherboard_id, cache_size_id);
ALTER TABLE motherboard_dram_type ADD PRIMARY KEY (motherboard_id, dram_type_id);
ALTER TABLE motherboard_coprocessor ALTER motherboard_id SET NOT NULL;
ALTER TABLE motherboard_coprocessor ALTER coprocessor_id SET NOT NULL;
CREATE INDEX IDX_27036C4D6511E8A3 ON motherboard_coprocessor (motherboard_id);
CREATE INDEX IDX_27036C4D44EBDBAB ON motherboard_coprocessor (coprocessor_id);
ALTER TABLE motherboard_coprocessor ADD PRIMARY KEY (motherboard_id, coprocessor_id);
ALTER TABLE motherboard_known_issue ADD PRIMARY KEY (motherboard_id, known_issue_id);
ALTER TABLE motherboard_cpu_socket ALTER motherboard_id SET NOT NULL;
ALTER TABLE motherboard_cpu_socket ALTER cpu_socket_id SET NOT NULL;
CREATE INDEX IDX_8BF3B2736511E8A3 ON motherboard_cpu_socket (motherboard_id);
CREATE INDEX IDX_8BF3B2736B6A65A0 ON motherboard_cpu_socket (cpu_socket_id);
ALTER TABLE motherboard_cpu_socket ADD PRIMARY KEY (motherboard_id, cpu_socket_id);
ALTER TABLE motherboard_alias ADD PRIMARY KEY (id);
ALTER TABLE motherboard_bios ADD PRIMARY KEY (id);
ALTER TABLE motherboard_image ADD PRIMARY KEY (id);
ALTER TABLE motherboard_image_type ADD PRIMARY KEY (id);
ALTER TABLE motherboard_io_port ADD PRIMARY KEY (motherboard_id, io_port_id);
ALTER TABLE motherboard_max_ram ADD PRIMARY KEY (motherboard_id, max_ram_id);
ALTER TABLE "user" ADD PRIMARY KEY (id);
ALTER TABLE video_chipset ADD CONSTRAINT FK_C030A4F2A23B42D FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE video_chipset ADD PRIMARY KEY (id);
