<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20231008154632 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE trace_id_seq CASCADE');
        $this->addSql('CREATE TABLE audio_file_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_8ff57b5ffefc67092b18d44acbd1c748_idx ON audio_file_audit (type)');
        $this->addSql('CREATE INDEX object_id_8ff57b5ffefc67092b18d44acbd1c748_idx ON audio_file_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_8ff57b5ffefc67092b18d44acbd1c748_idx ON audio_file_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_8ff57b5ffefc67092b18d44acbd1c748_idx ON audio_file_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_8ff57b5ffefc67092b18d44acbd1c748_idx ON audio_file_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_8ff57b5ffefc67092b18d44acbd1c748_idx ON audio_file_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN audio_file_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE cache_size_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_29d1f10fa989ee84a448c9a96fddd85c_idx ON cache_size_audit (type)');
        $this->addSql('CREATE INDEX object_id_29d1f10fa989ee84a448c9a96fddd85c_idx ON cache_size_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_29d1f10fa989ee84a448c9a96fddd85c_idx ON cache_size_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_29d1f10fa989ee84a448c9a96fddd85c_idx ON cache_size_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_29d1f10fa989ee84a448c9a96fddd85c_idx ON cache_size_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_29d1f10fa989ee84a448c9a96fddd85c_idx ON cache_size_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN cache_size_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE cd_drive_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_9f8dec18b5fb7e24b7c94e8fbda50935_idx ON cd_drive_audit (type)');
        $this->addSql('CREATE INDEX object_id_9f8dec18b5fb7e24b7c94e8fbda50935_idx ON cd_drive_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_9f8dec18b5fb7e24b7c94e8fbda50935_idx ON cd_drive_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_9f8dec18b5fb7e24b7c94e8fbda50935_idx ON cd_drive_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_9f8dec18b5fb7e24b7c94e8fbda50935_idx ON cd_drive_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_9f8dec18b5fb7e24b7c94e8fbda50935_idx ON cd_drive_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN cd_drive_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE chip_alias_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_0e06f0abb4bd665867ff915f00aa0eef_idx ON chip_alias_audit (type)');
        $this->addSql('CREATE INDEX object_id_0e06f0abb4bd665867ff915f00aa0eef_idx ON chip_alias_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_0e06f0abb4bd665867ff915f00aa0eef_idx ON chip_alias_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_0e06f0abb4bd665867ff915f00aa0eef_idx ON chip_alias_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_0e06f0abb4bd665867ff915f00aa0eef_idx ON chip_alias_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_0e06f0abb4bd665867ff915f00aa0eef_idx ON chip_alias_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN chip_alias_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE chip_documentation_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_fa0b8c290db3c147e3ff77b1c0eb051a_idx ON chip_documentation_audit (type)');
        $this->addSql('CREATE INDEX object_id_fa0b8c290db3c147e3ff77b1c0eb051a_idx ON chip_documentation_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_fa0b8c290db3c147e3ff77b1c0eb051a_idx ON chip_documentation_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_fa0b8c290db3c147e3ff77b1c0eb051a_idx ON chip_documentation_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_fa0b8c290db3c147e3ff77b1c0eb051a_idx ON chip_documentation_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_fa0b8c290db3c147e3ff77b1c0eb051a_idx ON chip_documentation_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN chip_documentation_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE chip_image_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_6a38ebe66df3f074d7d84f451d844d75_idx ON chip_image_audit (type)');
        $this->addSql('CREATE INDEX object_id_6a38ebe66df3f074d7d84f451d844d75_idx ON chip_image_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_6a38ebe66df3f074d7d84f451d844d75_idx ON chip_image_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_6a38ebe66df3f074d7d84f451d844d75_idx ON chip_image_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_6a38ebe66df3f074d7d84f451d844d75_idx ON chip_image_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_6a38ebe66df3f074d7d84f451d844d75_idx ON chip_image_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN chip_image_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE chipset_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_61d2035e8d91a72ba25ce70d2f63b0ec_idx ON chipset_audit (type)');
        $this->addSql('CREATE INDEX object_id_61d2035e8d91a72ba25ce70d2f63b0ec_idx ON chipset_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_61d2035e8d91a72ba25ce70d2f63b0ec_idx ON chipset_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_61d2035e8d91a72ba25ce70d2f63b0ec_idx ON chipset_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_61d2035e8d91a72ba25ce70d2f63b0ec_idx ON chipset_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_61d2035e8d91a72ba25ce70d2f63b0ec_idx ON chipset_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN chipset_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE chipset_alias_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_bcd97970cc61a242a2f9f5b4a4885710_idx ON chipset_alias_audit (type)');
        $this->addSql('CREATE INDEX object_id_bcd97970cc61a242a2f9f5b4a4885710_idx ON chipset_alias_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_bcd97970cc61a242a2f9f5b4a4885710_idx ON chipset_alias_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_bcd97970cc61a242a2f9f5b4a4885710_idx ON chipset_alias_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_bcd97970cc61a242a2f9f5b4a4885710_idx ON chipset_alias_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_bcd97970cc61a242a2f9f5b4a4885710_idx ON chipset_alias_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN chipset_alias_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE chipset_bios_code_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_cc82f08d5cf8dc6550d1ee8d1a01239b_idx ON chipset_bios_code_audit (type)');
        $this->addSql('CREATE INDEX object_id_cc82f08d5cf8dc6550d1ee8d1a01239b_idx ON chipset_bios_code_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_cc82f08d5cf8dc6550d1ee8d1a01239b_idx ON chipset_bios_code_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_cc82f08d5cf8dc6550d1ee8d1a01239b_idx ON chipset_bios_code_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_cc82f08d5cf8dc6550d1ee8d1a01239b_idx ON chipset_bios_code_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_cc82f08d5cf8dc6550d1ee8d1a01239b_idx ON chipset_bios_code_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN chipset_bios_code_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE chipset_documentation_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_8670f929bdf4c2612b0b2abe9f7ee4c3_idx ON chipset_documentation_audit (type)');
        $this->addSql('CREATE INDEX object_id_8670f929bdf4c2612b0b2abe9f7ee4c3_idx ON chipset_documentation_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_8670f929bdf4c2612b0b2abe9f7ee4c3_idx ON chipset_documentation_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_8670f929bdf4c2612b0b2abe9f7ee4c3_idx ON chipset_documentation_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_8670f929bdf4c2612b0b2abe9f7ee4c3_idx ON chipset_documentation_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_8670f929bdf4c2612b0b2abe9f7ee4c3_idx ON chipset_documentation_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN chipset_documentation_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE cpu_socket_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_6ba020da69afbde714d30fba41da63d1_idx ON cpu_socket_audit (type)');
        $this->addSql('CREATE INDEX object_id_6ba020da69afbde714d30fba41da63d1_idx ON cpu_socket_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_6ba020da69afbde714d30fba41da63d1_idx ON cpu_socket_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_6ba020da69afbde714d30fba41da63d1_idx ON cpu_socket_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_6ba020da69afbde714d30fba41da63d1_idx ON cpu_socket_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_6ba020da69afbde714d30fba41da63d1_idx ON cpu_socket_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN cpu_socket_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE creditor_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_fc9bec196da53ce7a602fc0a78eb6d9f_idx ON creditor_audit (type)');
        $this->addSql('CREATE INDEX object_id_fc9bec196da53ce7a602fc0a78eb6d9f_idx ON creditor_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_fc9bec196da53ce7a602fc0a78eb6d9f_idx ON creditor_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_fc9bec196da53ce7a602fc0a78eb6d9f_idx ON creditor_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_fc9bec196da53ce7a602fc0a78eb6d9f_idx ON creditor_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_fc9bec196da53ce7a602fc0a78eb6d9f_idx ON creditor_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN creditor_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE dram_type_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_582e3a1faf6ac4ffd63dd5bb3ec8cc84_idx ON dram_type_audit (type)');
        $this->addSql('CREATE INDEX object_id_582e3a1faf6ac4ffd63dd5bb3ec8cc84_idx ON dram_type_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_582e3a1faf6ac4ffd63dd5bb3ec8cc84_idx ON dram_type_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_582e3a1faf6ac4ffd63dd5bb3ec8cc84_idx ON dram_type_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_582e3a1faf6ac4ffd63dd5bb3ec8cc84_idx ON dram_type_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_582e3a1faf6ac4ffd63dd5bb3ec8cc84_idx ON dram_type_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN dram_type_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE expansion_chip_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_960347c7fe84eb6e28aed809aa9c7776_idx ON expansion_chip_audit (type)');
        $this->addSql('CREATE INDEX object_id_960347c7fe84eb6e28aed809aa9c7776_idx ON expansion_chip_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_960347c7fe84eb6e28aed809aa9c7776_idx ON expansion_chip_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_960347c7fe84eb6e28aed809aa9c7776_idx ON expansion_chip_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_960347c7fe84eb6e28aed809aa9c7776_idx ON expansion_chip_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_960347c7fe84eb6e28aed809aa9c7776_idx ON expansion_chip_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN expansion_chip_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE expansion_slot_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_691bdfd6223afda19fd3a63d601ffc81_idx ON expansion_slot_audit (type)');
        $this->addSql('CREATE INDEX object_id_691bdfd6223afda19fd3a63d601ffc81_idx ON expansion_slot_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_691bdfd6223afda19fd3a63d601ffc81_idx ON expansion_slot_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_691bdfd6223afda19fd3a63d601ffc81_idx ON expansion_slot_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_691bdfd6223afda19fd3a63d601ffc81_idx ON expansion_slot_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_691bdfd6223afda19fd3a63d601ffc81_idx ON expansion_slot_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN expansion_slot_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE floppy_drive_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_fd4fbb55ac25008a69e2b46f8b7b090f_idx ON floppy_drive_audit (type)');
        $this->addSql('CREATE INDEX object_id_fd4fbb55ac25008a69e2b46f8b7b090f_idx ON floppy_drive_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_fd4fbb55ac25008a69e2b46f8b7b090f_idx ON floppy_drive_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_fd4fbb55ac25008a69e2b46f8b7b090f_idx ON floppy_drive_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_fd4fbb55ac25008a69e2b46f8b7b090f_idx ON floppy_drive_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_fd4fbb55ac25008a69e2b46f8b7b090f_idx ON floppy_drive_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN floppy_drive_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE form_factor_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_eee98266504eb2fe1a55016781b90563_idx ON form_factor_audit (type)');
        $this->addSql('CREATE INDEX object_id_eee98266504eb2fe1a55016781b90563_idx ON form_factor_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_eee98266504eb2fe1a55016781b90563_idx ON form_factor_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_eee98266504eb2fe1a55016781b90563_idx ON form_factor_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_eee98266504eb2fe1a55016781b90563_idx ON form_factor_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_eee98266504eb2fe1a55016781b90563_idx ON form_factor_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN form_factor_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE hard_drive_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_3b720b21b53f924dc583f5c3d1ff06f7_idx ON hard_drive_audit (type)');
        $this->addSql('CREATE INDEX object_id_3b720b21b53f924dc583f5c3d1ff06f7_idx ON hard_drive_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_3b720b21b53f924dc583f5c3d1ff06f7_idx ON hard_drive_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_3b720b21b53f924dc583f5c3d1ff06f7_idx ON hard_drive_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_3b720b21b53f924dc583f5c3d1ff06f7_idx ON hard_drive_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_3b720b21b53f924dc583f5c3d1ff06f7_idx ON hard_drive_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN hard_drive_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE instruction_set_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_d391fee31d1b6f9efb081f09c8a179d2_idx ON instruction_set_audit (type)');
        $this->addSql('CREATE INDEX object_id_d391fee31d1b6f9efb081f09c8a179d2_idx ON instruction_set_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_d391fee31d1b6f9efb081f09c8a179d2_idx ON instruction_set_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_d391fee31d1b6f9efb081f09c8a179d2_idx ON instruction_set_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_d391fee31d1b6f9efb081f09c8a179d2_idx ON instruction_set_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_d391fee31d1b6f9efb081f09c8a179d2_idx ON instruction_set_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN instruction_set_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE io_port_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_a75d64d02c8769a5472caec18058a94c_idx ON io_port_audit (type)');
        $this->addSql('CREATE INDEX object_id_a75d64d02c8769a5472caec18058a94c_idx ON io_port_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a75d64d02c8769a5472caec18058a94c_idx ON io_port_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a75d64d02c8769a5472caec18058a94c_idx ON io_port_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a75d64d02c8769a5472caec18058a94c_idx ON io_port_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a75d64d02c8769a5472caec18058a94c_idx ON io_port_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN io_port_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE known_issue_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_8b80ae7dcde7160fcab7fc17785cc4a0_idx ON known_issue_audit (type)');
        $this->addSql('CREATE INDEX object_id_8b80ae7dcde7160fcab7fc17785cc4a0_idx ON known_issue_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_8b80ae7dcde7160fcab7fc17785cc4a0_idx ON known_issue_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_8b80ae7dcde7160fcab7fc17785cc4a0_idx ON known_issue_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_8b80ae7dcde7160fcab7fc17785cc4a0_idx ON known_issue_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_8b80ae7dcde7160fcab7fc17785cc4a0_idx ON known_issue_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN known_issue_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE large_file_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_acf0fb17699f17c0fec9f166a6167f58_idx ON large_file_audit (type)');
        $this->addSql('CREATE INDEX object_id_acf0fb17699f17c0fec9f166a6167f58_idx ON large_file_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_acf0fb17699f17c0fec9f166a6167f58_idx ON large_file_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_acf0fb17699f17c0fec9f166a6167f58_idx ON large_file_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_acf0fb17699f17c0fec9f166a6167f58_idx ON large_file_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_acf0fb17699f17c0fec9f166a6167f58_idx ON large_file_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN large_file_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE large_file_chipset_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_0fd67c3263b4dd16747c92d03aaddd5a_idx ON large_file_chipset_audit (type)');
        $this->addSql('CREATE INDEX object_id_0fd67c3263b4dd16747c92d03aaddd5a_idx ON large_file_chipset_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_0fd67c3263b4dd16747c92d03aaddd5a_idx ON large_file_chipset_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_0fd67c3263b4dd16747c92d03aaddd5a_idx ON large_file_chipset_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_0fd67c3263b4dd16747c92d03aaddd5a_idx ON large_file_chipset_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_0fd67c3263b4dd16747c92d03aaddd5a_idx ON large_file_chipset_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN large_file_chipset_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE large_file_expansion_chip_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_3d9ce2a6398bff4ea7983b2047510f58_idx ON large_file_expansion_chip_audit (type)');
        $this->addSql('CREATE INDEX object_id_3d9ce2a6398bff4ea7983b2047510f58_idx ON large_file_expansion_chip_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_3d9ce2a6398bff4ea7983b2047510f58_idx ON large_file_expansion_chip_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_3d9ce2a6398bff4ea7983b2047510f58_idx ON large_file_expansion_chip_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_3d9ce2a6398bff4ea7983b2047510f58_idx ON large_file_expansion_chip_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_3d9ce2a6398bff4ea7983b2047510f58_idx ON large_file_expansion_chip_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN large_file_expansion_chip_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE large_file_media_type_flag_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_3513e78b4c2d3d39e7e153d9cef36f6f_idx ON large_file_media_type_flag_audit (type)');
        $this->addSql('CREATE INDEX object_id_3513e78b4c2d3d39e7e153d9cef36f6f_idx ON large_file_media_type_flag_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_3513e78b4c2d3d39e7e153d9cef36f6f_idx ON large_file_media_type_flag_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_3513e78b4c2d3d39e7e153d9cef36f6f_idx ON large_file_media_type_flag_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_3513e78b4c2d3d39e7e153d9cef36f6f_idx ON large_file_media_type_flag_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_3513e78b4c2d3d39e7e153d9cef36f6f_idx ON large_file_media_type_flag_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN large_file_media_type_flag_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE large_file_motherboard_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_fd26ba9c2a6d4ef25d9b0d3ad44cd5ac_idx ON large_file_motherboard_audit (type)');
        $this->addSql('CREATE INDEX object_id_fd26ba9c2a6d4ef25d9b0d3ad44cd5ac_idx ON large_file_motherboard_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_fd26ba9c2a6d4ef25d9b0d3ad44cd5ac_idx ON large_file_motherboard_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_fd26ba9c2a6d4ef25d9b0d3ad44cd5ac_idx ON large_file_motherboard_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_fd26ba9c2a6d4ef25d9b0d3ad44cd5ac_idx ON large_file_motherboard_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_fd26ba9c2a6d4ef25d9b0d3ad44cd5ac_idx ON large_file_motherboard_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN large_file_motherboard_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE license_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_169e9280a5681d5290d2feade49fce0f_idx ON license_audit (type)');
        $this->addSql('CREATE INDEX object_id_169e9280a5681d5290d2feade49fce0f_idx ON license_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_169e9280a5681d5290d2feade49fce0f_idx ON license_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_169e9280a5681d5290d2feade49fce0f_idx ON license_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_169e9280a5681d5290d2feade49fce0f_idx ON license_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_169e9280a5681d5290d2feade49fce0f_idx ON license_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN license_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE manual_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_5eebd732e1b8244f80b4840cb5ca2b0f_idx ON manual_audit (type)');
        $this->addSql('CREATE INDEX object_id_5eebd732e1b8244f80b4840cb5ca2b0f_idx ON manual_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_5eebd732e1b8244f80b4840cb5ca2b0f_idx ON manual_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_5eebd732e1b8244f80b4840cb5ca2b0f_idx ON manual_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_5eebd732e1b8244f80b4840cb5ca2b0f_idx ON manual_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_5eebd732e1b8244f80b4840cb5ca2b0f_idx ON manual_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN manual_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE manufacturer_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_a0bddd01ae8283b495d4724a84513130_idx ON manufacturer_audit (type)');
        $this->addSql('CREATE INDEX object_id_a0bddd01ae8283b495d4724a84513130_idx ON manufacturer_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a0bddd01ae8283b495d4724a84513130_idx ON manufacturer_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a0bddd01ae8283b495d4724a84513130_idx ON manufacturer_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a0bddd01ae8283b495d4724a84513130_idx ON manufacturer_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a0bddd01ae8283b495d4724a84513130_idx ON manufacturer_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN manufacturer_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE manufacturer_bios_manufacturer_code_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_acd1955d2ed7e7c974698096e21b0b4c_idx ON manufacturer_bios_manufacturer_code_audit (type)');
        $this->addSql('CREATE INDEX object_id_acd1955d2ed7e7c974698096e21b0b4c_idx ON manufacturer_bios_manufacturer_code_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_acd1955d2ed7e7c974698096e21b0b4c_idx ON manufacturer_bios_manufacturer_code_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_acd1955d2ed7e7c974698096e21b0b4c_idx ON manufacturer_bios_manufacturer_code_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_acd1955d2ed7e7c974698096e21b0b4c_idx ON manufacturer_bios_manufacturer_code_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_acd1955d2ed7e7c974698096e21b0b4c_idx ON manufacturer_bios_manufacturer_code_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN manufacturer_bios_manufacturer_code_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE max_ram_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_b93c893e752adc535757cf0876cd0e9b_idx ON max_ram_audit (type)');
        $this->addSql('CREATE INDEX object_id_b93c893e752adc535757cf0876cd0e9b_idx ON max_ram_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_b93c893e752adc535757cf0876cd0e9b_idx ON max_ram_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_b93c893e752adc535757cf0876cd0e9b_idx ON max_ram_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_b93c893e752adc535757cf0876cd0e9b_idx ON max_ram_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_b93c893e752adc535757cf0876cd0e9b_idx ON max_ram_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN max_ram_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE media_type_flag_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_507644644feed4277a39e25d4336dbd5_idx ON media_type_flag_audit (type)');
        $this->addSql('CREATE INDEX object_id_507644644feed4277a39e25d4336dbd5_idx ON media_type_flag_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_507644644feed4277a39e25d4336dbd5_idx ON media_type_flag_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_507644644feed4277a39e25d4336dbd5_idx ON media_type_flag_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_507644644feed4277a39e25d4336dbd5_idx ON media_type_flag_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_507644644feed4277a39e25d4336dbd5_idx ON media_type_flag_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN media_type_flag_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE misc_file_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_150f5aae28a21bf0a4de8736082960e4_idx ON misc_file_audit (type)');
        $this->addSql('CREATE INDEX object_id_150f5aae28a21bf0a4de8736082960e4_idx ON misc_file_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_150f5aae28a21bf0a4de8736082960e4_idx ON misc_file_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_150f5aae28a21bf0a4de8736082960e4_idx ON misc_file_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_150f5aae28a21bf0a4de8736082960e4_idx ON misc_file_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_150f5aae28a21bf0a4de8736082960e4_idx ON misc_file_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN misc_file_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_4f62493567bb67aa7f148ecdba508582_idx ON motherboard_audit (type)');
        $this->addSql('CREATE INDEX object_id_4f62493567bb67aa7f148ecdba508582_idx ON motherboard_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_4f62493567bb67aa7f148ecdba508582_idx ON motherboard_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_4f62493567bb67aa7f148ecdba508582_idx ON motherboard_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_4f62493567bb67aa7f148ecdba508582_idx ON motherboard_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_4f62493567bb67aa7f148ecdba508582_idx ON motherboard_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_alias_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_dda59cdbe5591f53545f3d3cb8f2a581_idx ON motherboard_alias_audit (type)');
        $this->addSql('CREATE INDEX object_id_dda59cdbe5591f53545f3d3cb8f2a581_idx ON motherboard_alias_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_dda59cdbe5591f53545f3d3cb8f2a581_idx ON motherboard_alias_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_dda59cdbe5591f53545f3d3cb8f2a581_idx ON motherboard_alias_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_dda59cdbe5591f53545f3d3cb8f2a581_idx ON motherboard_alias_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_dda59cdbe5591f53545f3d3cb8f2a581_idx ON motherboard_alias_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_alias_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_bios_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_e21de891fcf078bdf80c9da6a2a8302b_idx ON motherboard_bios_audit (type)');
        $this->addSql('CREATE INDEX object_id_e21de891fcf078bdf80c9da6a2a8302b_idx ON motherboard_bios_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e21de891fcf078bdf80c9da6a2a8302b_idx ON motherboard_bios_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e21de891fcf078bdf80c9da6a2a8302b_idx ON motherboard_bios_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e21de891fcf078bdf80c9da6a2a8302b_idx ON motherboard_bios_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e21de891fcf078bdf80c9da6a2a8302b_idx ON motherboard_bios_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_bios_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_expansion_slot_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_628be4deb0c202c253943ca05ead4ced_idx ON motherboard_expansion_slot_audit (type)');
        $this->addSql('CREATE INDEX object_id_628be4deb0c202c253943ca05ead4ced_idx ON motherboard_expansion_slot_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_628be4deb0c202c253943ca05ead4ced_idx ON motherboard_expansion_slot_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_628be4deb0c202c253943ca05ead4ced_idx ON motherboard_expansion_slot_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_628be4deb0c202c253943ca05ead4ced_idx ON motherboard_expansion_slot_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_628be4deb0c202c253943ca05ead4ced_idx ON motherboard_expansion_slot_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_expansion_slot_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_id_redirection_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_0eed096a24e20d2417fc69229b82826b_idx ON motherboard_id_redirection_audit (type)');
        $this->addSql('CREATE INDEX object_id_0eed096a24e20d2417fc69229b82826b_idx ON motherboard_id_redirection_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_0eed096a24e20d2417fc69229b82826b_idx ON motherboard_id_redirection_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_0eed096a24e20d2417fc69229b82826b_idx ON motherboard_id_redirection_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_0eed096a24e20d2417fc69229b82826b_idx ON motherboard_id_redirection_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_0eed096a24e20d2417fc69229b82826b_idx ON motherboard_id_redirection_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_id_redirection_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_image_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_58a74406ccdce9877cccced22104f177_idx ON motherboard_image_audit (type)');
        $this->addSql('CREATE INDEX object_id_58a74406ccdce9877cccced22104f177_idx ON motherboard_image_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_58a74406ccdce9877cccced22104f177_idx ON motherboard_image_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_58a74406ccdce9877cccced22104f177_idx ON motherboard_image_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_58a74406ccdce9877cccced22104f177_idx ON motherboard_image_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_58a74406ccdce9877cccced22104f177_idx ON motherboard_image_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_image_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_io_port_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_a302a576568b25b30ddf9b46823242a7_idx ON motherboard_io_port_audit (type)');
        $this->addSql('CREATE INDEX object_id_a302a576568b25b30ddf9b46823242a7_idx ON motherboard_io_port_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a302a576568b25b30ddf9b46823242a7_idx ON motherboard_io_port_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a302a576568b25b30ddf9b46823242a7_idx ON motherboard_io_port_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a302a576568b25b30ddf9b46823242a7_idx ON motherboard_io_port_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a302a576568b25b30ddf9b46823242a7_idx ON motherboard_io_port_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_io_port_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE motherboard_max_ram_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_aada2a54c3fd10d1f6b71488e89f51ff_idx ON motherboard_max_ram_audit (type)');
        $this->addSql('CREATE INDEX object_id_aada2a54c3fd10d1f6b71488e89f51ff_idx ON motherboard_max_ram_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_aada2a54c3fd10d1f6b71488e89f51ff_idx ON motherboard_max_ram_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_aada2a54c3fd10d1f6b71488e89f51ff_idx ON motherboard_max_ram_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_aada2a54c3fd10d1f6b71488e89f51ff_idx ON motherboard_max_ram_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_aada2a54c3fd10d1f6b71488e89f51ff_idx ON motherboard_max_ram_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN motherboard_max_ram_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE os_flag_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_aa7f44ae67f5af6edc02d91d068046dd_idx ON os_flag_audit (type)');
        $this->addSql('CREATE INDEX object_id_aa7f44ae67f5af6edc02d91d068046dd_idx ON os_flag_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_aa7f44ae67f5af6edc02d91d068046dd_idx ON os_flag_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_aa7f44ae67f5af6edc02d91d068046dd_idx ON os_flag_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_aa7f44ae67f5af6edc02d91d068046dd_idx ON os_flag_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_aa7f44ae67f5af6edc02d91d068046dd_idx ON os_flag_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN os_flag_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE processor_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_b6d6286db8bd767f58132d82dc1cfe3b_idx ON processor_audit (type)');
        $this->addSql('CREATE INDEX object_id_b6d6286db8bd767f58132d82dc1cfe3b_idx ON processor_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_b6d6286db8bd767f58132d82dc1cfe3b_idx ON processor_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_b6d6286db8bd767f58132d82dc1cfe3b_idx ON processor_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_b6d6286db8bd767f58132d82dc1cfe3b_idx ON processor_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_b6d6286db8bd767f58132d82dc1cfe3b_idx ON processor_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN processor_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE processor_platform_type_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_d314a98e9688653298d6c50fad51db0a_idx ON processor_platform_type_audit (type)');
        $this->addSql('CREATE INDEX object_id_d314a98e9688653298d6c50fad51db0a_idx ON processor_platform_type_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_d314a98e9688653298d6c50fad51db0a_idx ON processor_platform_type_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_d314a98e9688653298d6c50fad51db0a_idx ON processor_platform_type_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_d314a98e9688653298d6c50fad51db0a_idx ON processor_platform_type_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_d314a98e9688653298d6c50fad51db0a_idx ON processor_platform_type_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN processor_platform_type_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE processor_voltage_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_e9f5f3e8617d2db8c5e26a498ea2d3d4_idx ON processor_voltage_audit (type)');
        $this->addSql('CREATE INDEX object_id_e9f5f3e8617d2db8c5e26a498ea2d3d4_idx ON processor_voltage_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e9f5f3e8617d2db8c5e26a498ea2d3d4_idx ON processor_voltage_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e9f5f3e8617d2db8c5e26a498ea2d3d4_idx ON processor_voltage_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e9f5f3e8617d2db8c5e26a498ea2d3d4_idx ON processor_voltage_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e9f5f3e8617d2db8c5e26a498ea2d3d4_idx ON processor_voltage_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN processor_voltage_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE psuconnector_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_e60e76421cbbd9d5b279243d3b8cc261_idx ON psuconnector_audit (type)');
        $this->addSql('CREATE INDEX object_id_e60e76421cbbd9d5b279243d3b8cc261_idx ON psuconnector_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e60e76421cbbd9d5b279243d3b8cc261_idx ON psuconnector_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e60e76421cbbd9d5b279243d3b8cc261_idx ON psuconnector_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e60e76421cbbd9d5b279243d3b8cc261_idx ON psuconnector_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e60e76421cbbd9d5b279243d3b8cc261_idx ON psuconnector_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN psuconnector_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE storage_device_alias_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_a1a4e1bae230678bf9d26c880d0ae422_idx ON storage_device_alias_audit (type)');
        $this->addSql('CREATE INDEX object_id_a1a4e1bae230678bf9d26c880d0ae422_idx ON storage_device_alias_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a1a4e1bae230678bf9d26c880d0ae422_idx ON storage_device_alias_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a1a4e1bae230678bf9d26c880d0ae422_idx ON storage_device_alias_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a1a4e1bae230678bf9d26c880d0ae422_idx ON storage_device_alias_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a1a4e1bae230678bf9d26c880d0ae422_idx ON storage_device_alias_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN storage_device_alias_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE storage_device_documentation_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_065a2e1c250cdc4a971bdc3b429da5b7_idx ON storage_device_documentation_audit (type)');
        $this->addSql('CREATE INDEX object_id_065a2e1c250cdc4a971bdc3b429da5b7_idx ON storage_device_documentation_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_065a2e1c250cdc4a971bdc3b429da5b7_idx ON storage_device_documentation_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_065a2e1c250cdc4a971bdc3b429da5b7_idx ON storage_device_documentation_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_065a2e1c250cdc4a971bdc3b429da5b7_idx ON storage_device_documentation_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_065a2e1c250cdc4a971bdc3b429da5b7_idx ON storage_device_documentation_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN storage_device_documentation_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE storage_device_image_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_a0a526ae96124f15018100d2b6dada3f_idx ON storage_device_image_audit (type)');
        $this->addSql('CREATE INDEX object_id_a0a526ae96124f15018100d2b6dada3f_idx ON storage_device_image_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a0a526ae96124f15018100d2b6dada3f_idx ON storage_device_image_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a0a526ae96124f15018100d2b6dada3f_idx ON storage_device_image_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a0a526ae96124f15018100d2b6dada3f_idx ON storage_device_image_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a0a526ae96124f15018100d2b6dada3f_idx ON storage_device_image_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN storage_device_image_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE storage_device_interface_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_26eef752d26b4208a43cfc18a677123c_idx ON storage_device_interface_audit (type)');
        $this->addSql('CREATE INDEX object_id_26eef752d26b4208a43cfc18a677123c_idx ON storage_device_interface_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_26eef752d26b4208a43cfc18a677123c_idx ON storage_device_interface_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_26eef752d26b4208a43cfc18a677123c_idx ON storage_device_interface_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_26eef752d26b4208a43cfc18a677123c_idx ON storage_device_interface_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_26eef752d26b4208a43cfc18a677123c_idx ON storage_device_interface_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN storage_device_interface_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE storage_device_size_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_823ec0717761eb674dc2ccff812df089_idx ON storage_device_size_audit (type)');
        $this->addSql('CREATE INDEX object_id_823ec0717761eb674dc2ccff812df089_idx ON storage_device_size_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_823ec0717761eb674dc2ccff812df089_idx ON storage_device_size_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_823ec0717761eb674dc2ccff812df089_idx ON storage_device_size_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_823ec0717761eb674dc2ccff812df089_idx ON storage_device_size_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_823ec0717761eb674dc2ccff812df089_idx ON storage_device_size_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN storage_device_size_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE user_audit (id SERIAL NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX type_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (type)');
        $this->addSql('CREATE INDEX object_id_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (created_at)');
        $this->addSql('COMMENT ON COLUMN user_audit.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP TABLE trace');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SEQUENCE trace_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE trace (id INT NOT NULL, username VARCHAR(255) NOT NULL, event_type VARCHAR(255) NOT NULL, object_type VARCHAR(255) NOT NULL, object_id INT DEFAULT NULL, content VARCHAR(10000) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('DROP TABLE audio_file_audit');
        $this->addSql('DROP TABLE cache_size_audit');
        $this->addSql('DROP TABLE cd_drive_audit');
        $this->addSql('DROP TABLE chip_alias_audit');
        $this->addSql('DROP TABLE chip_documentation_audit');
        $this->addSql('DROP TABLE chip_image_audit');
        $this->addSql('DROP TABLE chipset_audit');
        $this->addSql('DROP TABLE chipset_alias_audit');
        $this->addSql('DROP TABLE chipset_bios_code_audit');
        $this->addSql('DROP TABLE chipset_documentation_audit');
        $this->addSql('DROP TABLE cpu_socket_audit');
        $this->addSql('DROP TABLE creditor_audit');
        $this->addSql('DROP TABLE dram_type_audit');
        $this->addSql('DROP TABLE expansion_chip_audit');
        $this->addSql('DROP TABLE expansion_slot_audit');
        $this->addSql('DROP TABLE floppy_drive_audit');
        $this->addSql('DROP TABLE form_factor_audit');
        $this->addSql('DROP TABLE hard_drive_audit');
        $this->addSql('DROP TABLE instruction_set_audit');
        $this->addSql('DROP TABLE io_port_audit');
        $this->addSql('DROP TABLE known_issue_audit');
        $this->addSql('DROP TABLE large_file_audit');
        $this->addSql('DROP TABLE large_file_chipset_audit');
        $this->addSql('DROP TABLE large_file_expansion_chip_audit');
        $this->addSql('DROP TABLE large_file_media_type_flag_audit');
        $this->addSql('DROP TABLE large_file_motherboard_audit');
        $this->addSql('DROP TABLE license_audit');
        $this->addSql('DROP TABLE manual_audit');
        $this->addSql('DROP TABLE manufacturer_audit');
        $this->addSql('DROP TABLE manufacturer_bios_manufacturer_code_audit');
        $this->addSql('DROP TABLE max_ram_audit');
        $this->addSql('DROP TABLE media_type_flag_audit');
        $this->addSql('DROP TABLE misc_file_audit');
        $this->addSql('DROP TABLE motherboard_audit');
        $this->addSql('DROP TABLE motherboard_alias_audit');
        $this->addSql('DROP TABLE motherboard_bios_audit');
        $this->addSql('DROP TABLE motherboard_expansion_slot_audit');
        $this->addSql('DROP TABLE motherboard_id_redirection_audit');
        $this->addSql('DROP TABLE motherboard_image_audit');
        $this->addSql('DROP TABLE motherboard_io_port_audit');
        $this->addSql('DROP TABLE motherboard_max_ram_audit');
        $this->addSql('DROP TABLE os_flag_audit');
        $this->addSql('DROP TABLE processor_audit');
        $this->addSql('DROP TABLE processor_platform_type_audit');
        $this->addSql('DROP TABLE processor_voltage_audit');
        $this->addSql('DROP TABLE psuconnector_audit');
        $this->addSql('DROP TABLE storage_device_alias_audit');
        $this->addSql('DROP TABLE storage_device_documentation_audit');
        $this->addSql('DROP TABLE storage_device_image_audit');
        $this->addSql('DROP TABLE storage_device_interface_audit');
        $this->addSql('DROP TABLE storage_device_size_audit');
        $this->addSql('DROP TABLE user_audit');
    }
}
