# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.locales: en
    locale: en

    app.pagination.max: 100
    user_agent.crawlers: ['Discordbot','Twitterbot','Googlebot','Googlebot-Image','Bingbot','Slurp','DuckDuckBot','Baiduspider','Baiduspider-image','YandexBot','facebookexternalhit','www.qwant.com']

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\RedirectController:
        calls:
            - method: setContainer
              arguments: ['@service_container']
    App\BranchLoader\GitLoader:
        arguments:
            ['%kernel.project_dir%']
    App\DataCollector\GitDataCollector:
        tags:
            -
                name:     data_collector
                template: 'admin/macros/git.html.twig'
                # must match the value returned by the getName() method
                id: 'app.git_data_collector'
        public: false
    dh_auditor.role_checker: '@App\Audit\Security\RoleChecker'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
